### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by melflynn** [Onaconnapuna/OurSpace#3]
- [x] You'll probably want the post and comment content to be in your state
- [x] Are you planning to implement likes? I didn't see that in your MVP list or schema. If so, please update those accordingly 
- [x] ^ You may want to consider having the ids of comments and likes listed as a part of the post slice of state
- [x] Will you need any info on friends in your state?

**Comment by Onaconnapuna** [comment]
Thinking about the project more and more I’m realizing much of the points
you made; I’ll go back and update schema.
